[dependencies]
base = "0.11.1"
matchers = "https://github.com/kritzcreek/motoko-matchers#7f95f69ae9a399cedf161d90738db822f315c07e"
candid = "https://github.com/gekctek/motoko_candid#v1.0.1"
candy = "0.3.0"
xtendedNumbers = "https://github.com/gekctek/motoko_numbers#v1.0.2"
stablebuffer = "https://github.com/canscale/StableBuffer#v1.3.0@acdde6bb5b939227997cebdbb8919d2e6da8691c"
map = "https://github.com/ZhenyaUsenko/motoko-hash-map#v9.0.1@10b68f6ea8df5e72dfa4c07a50c8bb60a916c233"
