[package]
name = "candy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
candid = "0.8.4"
serde = "1.0.152"

[dev-dependencies]
pretty_assertions = "1.3.0"
